server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: yaron33
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

external-api:
  poll:
    name: "sa"
    url: "http://localhost:8081"

jwt:
  secret: your/jwt/secret/key123456789/012345678901234567890123456789
  expiration: 3600000